import { z } from "zod";
import { LUT_PRESET_IDS } from "./viewerPresets";
import type { Project3DConfig } from "./types";

const hexColorSchema = z.string().regex(/^#[0-9a-fA-F]{6}$/, "Expected a #rrggbb hex color");

const solarAnchorSchema = z.object({
  id: z.string().min(1),
  timeHours: z.number().min(0).max(24),
  elevationDeg: z.number().min(-90).max(90),
  azimuthDeg: z.number().min(0).max(360),
});

const FIELD_GROUPS = [
  {
    id: "sun-sky",
    label: "Sun & Sky",
    fields: {
      sunAzimuthDeg: z.number().min(0).max(360),
      sunElevationDeg: z.number().min(-90).max(90),
      solarControllerEnabled: z.boolean(),
      solarPathMode: z.enum(["manual", "geographic"]),
      viewerTimeControlEnabled: z.boolean(),
      viewerTimeHours: z.number().min(0).max(24),
      viewerTimeStartHours: z.number().min(0).max(24),
      viewerTimeEndHours: z.number().min(0).max(24),
      viewerTimeStepMinutes: z.number().int().min(1).max(240),
      solarAnchors: z.array(solarAnchorSchema).max(24),
      geoLatitude: z.number().min(-90).max(90),
      geoLongitude: z.number().min(-180).max(180),
      simulationDate: z.string().min(1),
      northOffsetDeg: z.number().min(-360).max(360),
      sunDiscEnabled: z.boolean(),
      autoSunIntensityEnabled: z.boolean(),
      autoSunColorEnabled: z.boolean(),
      manualSunIntensity: z.number().min(0).max(10),
      manualSunColorHex: hexColorSchema,
      environmentRefreshEnabled: z.boolean(),
      skyEnabled: z.boolean(),
      skyTurbidity: z.number().min(0).max(20),
      skyRayleigh: z.number().min(0).max(4),
      skyMieCoefficient: z.number().min(0).max(0.1),
      skyMieDirectionalG: z.number().min(0).max(1),
      sunLightEnabled: z.boolean(),
      sunTemperatureK: z.number().int().min(1000).max(40000),
    },
  },
  {
    id: "fog-haze",
    label: "Fog & Haze",
    fields: {
      fogEnabled: z.boolean(),
      fogColor: hexColorSchema,
      fogDensity: z.number().min(0).max(0.1),
      fogMatchesSky: z.boolean(),
      fogHeightBandEnabled: z.boolean(),
      fogHazeEnabled: z.boolean(),
      fogNoiseEnabled: z.boolean(),
      fogMovementEnabled: z.boolean(),
      fogSunInteractionEnabled: z.boolean(),
      fogBaseHeight: z.number().min(-500).max(2000),
      fogTopHeight: z.number().min(-500).max(2000),
      fogHaze: z.number().min(0).max(1),
      fogNoiseStrength: z.number().min(0).max(1),
      fogNoiseScale: z.number().min(0.0001).max(1),
      fogWindDirectionDeg: z.number().min(0).max(360),
      fogWindSpeed: z.number().min(0).max(2),
      fogFalloff: z.number().min(0.01).max(8),
      fogMaxOpacity: z.number().min(0).max(1),
    },
  },
  {
    id: "clouds",
    label: "Clouds",
    fields: {
      cloudsEnabled: z.boolean(),
      cloudCoverage: z.number().min(0).max(1),
      cloudDensity: z.number().min(0).max(1),
      cloudElevation: z.number().min(0).max(1),
      cloudMovementEnabled: z.boolean(),
      cloudSunLightingEnabled: z.boolean(),
      cloudShadowsEnabled: z.boolean(),
      cloudHeight: z.number().min(0).max(2000),
      cloudThickness: z.number().min(1).max(1000),
      cloudThreshold: z.number().min(0).max(1),
      cloudOpacity: z.number().min(0).max(1),
      cloudSoftness: z.number().min(0.01).max(1),
      cloudScale: z.number().min(0.0001).max(1),
      cloudWindSpeed: z.number().min(0).max(2),
      cloudWindDirectionDeg: z.number().min(0).max(360),
      cloudRaymarchSteps: z.number().int().min(1).max(24),
    },
  },
  {
    id: "water",
    label: "Water",
    fields: {
      waterEnabled: z.boolean(),
      waterDistortionScale: z.number().min(0).max(8),
      waterSize: z.number().min(0.1).max(10),
      waterType: z.enum(["sea", "lake", "pool", "decorative"]),
      waterWavesEnabled: z.boolean(),
      waterMovementEnabled: z.boolean(),
      waterSunReflectionEnabled: z.boolean(),
      waterEnvReflectionEnabled: z.boolean(),
      waterNormalMapEnabled: z.boolean(),
      waterHeight: z.number().min(-500).max(500),
      waterColor: hexColorSchema,
      waterDeepColor: hexColorSchema,
    },
  },
  {
    id: "lens-flare-bloom",
    label: "Lens Flare & Bloom",
    fields: {
      lensFlareEnabled: z.boolean(),
      lensFlareIntensity: z.number().min(0).max(3),
      bloomEnabled: z.boolean(),
      bloomStrength: z.number().min(0).max(3),
      bloomRadius: z.number().min(0).max(1),
    },
  },
  {
    id: "color-grading",
    label: "Tone Mapping & Color",
    fields: {
      exposure: z.number().min(0).max(4),
      toneMapping: z.enum(["none", "linear", "reinhard", "cineon", "aces", "agx", "neutral"]),
      lutEnabled: z.boolean(),
      lutPreset: z.enum(LUT_PRESET_IDS),
      lutIntensity: z.number().min(0).max(1),
    },
  },
] as const;

export const ENVIRONMENT_PRESET_FIELD_GROUPS = FIELD_GROUPS.map((g) => ({
  id: g.id,
  label: g.label,
  fieldNames: Object.keys(g.fields),
}));

export const environmentPresetConfigSchema = z.object(
  Object.assign({}, ...FIELD_GROUPS.map((g) => g.fields))
);

export type EnvironmentPresetConfig = z.infer<typeof environmentPresetConfigSchema>;

export function pickEnvironmentPresetConfig(draft: Project3DConfig): EnvironmentPresetConfig {
  return {
    sunAzimuthDeg: draft.sunAzimuthDeg,
    sunElevationDeg: draft.sunElevationDeg,
    solarControllerEnabled: draft.solarControllerEnabled,
    solarPathMode: draft.solarPathMode,
    viewerTimeControlEnabled: draft.viewerTimeControlEnabled,
    viewerTimeHours: draft.viewerTimeHours,
    viewerTimeStartHours: draft.viewerTimeStartHours,
    viewerTimeEndHours: draft.viewerTimeEndHours,
    viewerTimeStepMinutes: draft.viewerTimeStepMinutes,
    solarAnchors: draft.solarAnchors,
    geoLatitude: draft.geoLatitude,
    geoLongitude: draft.geoLongitude,
    simulationDate: draft.simulationDate,
    northOffsetDeg: draft.northOffsetDeg,
    sunDiscEnabled: draft.sunDiscEnabled,
    autoSunIntensityEnabled: draft.autoSunIntensityEnabled,
    autoSunColorEnabled: draft.autoSunColorEnabled,
    manualSunIntensity: draft.manualSunIntensity,
    manualSunColorHex: draft.manualSunColorHex,
    environmentRefreshEnabled: draft.environmentRefreshEnabled,
    skyEnabled: draft.skyEnabled,
    skyTurbidity: draft.skyTurbidity,
    skyRayleigh: draft.skyRayleigh,
    skyMieCoefficient: draft.skyMieCoefficient,
    skyMieDirectionalG: draft.skyMieDirectionalG,
    sunLightEnabled: draft.sunLightEnabled,
    sunTemperatureK: draft.sunTemperatureK,

    fogEnabled: draft.fogEnabled,
    fogColor: draft.fogColor,
    fogDensity: draft.fogDensity,
    fogMatchesSky: draft.fogMatchesSky,
    fogHeightBandEnabled: draft.fogHeightBandEnabled,
    fogHazeEnabled: draft.fogHazeEnabled,
    fogNoiseEnabled: draft.fogNoiseEnabled,
    fogMovementEnabled: draft.fogMovementEnabled,
    fogSunInteractionEnabled: draft.fogSunInteractionEnabled,
    fogBaseHeight: draft.fogBaseHeight,
    fogTopHeight: draft.fogTopHeight,
    fogHaze: draft.fogHaze,
    fogNoiseStrength: draft.fogNoiseStrength,
    fogNoiseScale: draft.fogNoiseScale,
    fogWindDirectionDeg: draft.fogWindDirectionDeg,
    fogWindSpeed: draft.fogWindSpeed,
    fogFalloff: draft.fogFalloff,
    fogMaxOpacity: draft.fogMaxOpacity,

    cloudsEnabled: draft.cloudsEnabled,
    cloudCoverage: draft.cloudCoverage,
    cloudDensity: draft.cloudDensity,
    cloudElevation: draft.cloudElevation,
    cloudMovementEnabled: draft.cloudMovementEnabled,
    cloudSunLightingEnabled: draft.cloudSunLightingEnabled,
    cloudShadowsEnabled: draft.cloudShadowsEnabled,
    cloudHeight: draft.cloudHeight,
    cloudThickness: draft.cloudThickness,
    cloudThreshold: draft.cloudThreshold,
    cloudOpacity: draft.cloudOpacity,
    cloudSoftness: draft.cloudSoftness,
    cloudScale: draft.cloudScale,
    cloudWindSpeed: draft.cloudWindSpeed,
    cloudWindDirectionDeg: draft.cloudWindDirectionDeg,
    cloudRaymarchSteps: draft.cloudRaymarchSteps,

    waterEnabled: draft.waterEnabled,
    waterDistortionScale: draft.waterDistortionScale,
    waterSize: draft.waterSize,
    waterType: draft.waterType,
    waterWavesEnabled: draft.waterWavesEnabled,
    waterMovementEnabled: draft.waterMovementEnabled,
    waterSunReflectionEnabled: draft.waterSunReflectionEnabled,
    waterEnvReflectionEnabled: draft.waterEnvReflectionEnabled,
    waterNormalMapEnabled: draft.waterNormalMapEnabled,
    waterHeight: draft.waterHeight,
    waterColor: draft.waterColor,
    waterDeepColor: draft.waterDeepColor,

    lensFlareEnabled: draft.lensFlareEnabled,
    lensFlareIntensity: draft.lensFlareIntensity,
    bloomEnabled: draft.bloomEnabled,
    bloomStrength: draft.bloomStrength,
    bloomRadius: draft.bloomRadius,

    exposure: draft.exposure,
    toneMapping: draft.toneMapping,
    lutEnabled: draft.lutEnabled,
    lutPreset: draft.lutPreset as EnvironmentPresetConfig["lutPreset"],
    lutIntensity: draft.lutIntensity,
  };
}
