-- AlterTable
ALTER TABLE "project_3d_configs" ADD COLUMN     "bloomEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "bloomRadius" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "bloomStrength" DOUBLE PRECISION NOT NULL DEFAULT 0.1,
ADD COLUMN     "cloudCoverage" DOUBLE PRECISION NOT NULL DEFAULT 0.4,
ADD COLUMN     "cloudDensity" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
ADD COLUMN     "cloudElevation" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
ADD COLUMN     "cloudsEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "waterDistortionScale" DOUBLE PRECISION NOT NULL DEFAULT 3.7,
ADD COLUMN     "waterEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "waterSize" DOUBLE PRECISION NOT NULL DEFAULT 1;

