-- AlterTable
ALTER TABLE "project_3d_configs" ADD COLUMN     "mapViewAltitude" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "mapViewEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "mapViewHeadingDeg" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "mapViewLatitude" DOUBLE PRECISION,
ADD COLUMN     "mapViewLongitude" DOUBLE PRECISION,
ADD COLUMN     "mapViewScale" DOUBLE PRECISION NOT NULL DEFAULT 1;
