import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/db";
import type { Prisma } from "@/generated/prisma";
import { requireAdmin } from "@/lib/adminAuth";
import { logAuditEvent } from "@/lib/audit";
import { refreshExperienceDocument } from "@/lib/experienceDocument";
import { LUT_PRESET_IDS } from "@/lib/viewerPresets";

const vector3Schema = z.object({ x: z.number(), y: z.number(), z: z.number() });

const cameraPresetSchema = z.object({
  id: z.string().min(1),
  label: z.string().min(1),
  position: vector3Schema,
  target: vector3Schema,
  fov: z.number().min(10).max(120),
  durationMs: z.number().min(0).max(10_000),
});

const viewerUISchema = z.object({
  home: z.boolean(),
  unitSearch: z.boolean(),
  hoverEnabled: z.boolean().optional(),
  selectEnabled: z.boolean().optional(),
  showUnitInfo: z.boolean().optional(),
  sectionsEnabled: z.boolean().optional(),
  sunPresetEnabled: z.boolean().optional(),
  unitInteractionEnabled: z.boolean().optional(),
  highlightEnabled: z.boolean().optional(),
  statusColorsEnabled: z.boolean().optional(),
  isolationEnabled: z.boolean().optional(),
  floorIsolationEnabled: z.boolean().optional(),
  unitPageLinkEnabled: z.boolean().optional(),
  filtersEnabled: z.boolean().optional(),
  filterFloorEnabled: z.boolean().optional(),
  filterAvailabilityEnabled: z.boolean().optional(),
  filterBedroomsEnabled: z.boolean().optional(),
  filterTypeEnabled: z.boolean().optional(),
  filterPriceEnabled: z.boolean().optional(),
  resetEnabled: z.boolean().optional(),
  fullscreenEnabled: z.boolean().optional(),
  shotsMenuEnabled: z.boolean().optional(),
  screenshotEnabled: z.boolean().optional(),
  shareEnabled: z.boolean().optional(),
});

const hexColorSchema = z.string().regex(/^#[0-9a-fA-F]{6}$/, "Expected a #rrggbb hex color");

const solarAnchorSchema = z.object({
  id: z.string().min(1),
  timeHours: z.number().min(0).max(24),
  elevationDeg: z.number().min(-90).max(90),
  azimuthDeg: z.number().min(0).max(360),
});

const artificialLightSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1).max(80),
  type: z.enum(["point", "spot", "ies", "rect"]),
  enabled: z.boolean(),
  shadowsEnabled: z.boolean(),
  volumetricEnabled: z.boolean(),
  helperEnabled: z.boolean(),
  position: vector3Schema,
  target: vector3Schema,
  colorHex: hexColorSchema,
  temperatureK: z.number().min(1000).max(40000).nullable(),
  intensity: z.number().min(0).max(1000),
  distance: z.number().min(0).max(2000),
  decay: z.number().min(0).max(4),
  angleDeg: z.number().min(0.1).max(89),
  penumbra: z.number().min(0).max(1),
  width: z.number().min(0.01).max(500),
  height: z.number().min(0.01).max(500),
  iesProfileUrl: z.string().url().nullable(),
});

const sectionSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  scope: z.enum(["project", "building"]),
  buildingName: z.string().optional(),
  centerX: z.number(),
  centerZ: z.number(),
  widthM: z.number().min(0).max(5000),
  depthM: z.number().min(0).max(5000),
  rotationDeg: z.number().min(-360).max(360),
  heightM: z.number().min(-50).max(500),
  bottomEnabled: z.boolean(),
  heightOnly: z.boolean().optional(),
  fillGapsEnabled: z.boolean(),
  fillColor: hexColorSchema,
  cameraPreset: z.object({ position: vector3Schema, target: vector3Schema, fov: z.number().min(10).max(120) }).optional(),
  floorId: z.string().optional(),
  hidden: z.boolean().optional(),
});

const patchSchema = z.object({
  groundEnabled: z.boolean().optional(),
  groundStyle: z.enum(["disc", "infinite"]).optional(),
  groundColor: hexColorSchema.optional(),
  groundFogEnabled: z.boolean().optional(),
  groundFogRadius: z.number().min(1).max(20_000).optional(),
  cameraStartDistanceMultiplier: z.number().positive().max(10).optional(),
  cameraMinDistanceMultiplier: z.number().positive().max(10).optional(),
  cameraMaxDistanceMultiplier: z.number().positive().max(20).optional(),
  cameraMaxPolarDeg: z.number().min(0).max(180).optional(),
  cameraMinPolarDeg: z.number().min(0).max(180).optional(),
  autoRotate: z.boolean().optional(),
  idleDroneEnabled: z.boolean().optional(),
  idleDroneDelaySec: z.number().min(5).max(600).optional(),
  idleDroneOrbitDurationSec: z.number().min(20).max(300).optional(),
  idleDroneClockwise: z.boolean().optional(),
  idleDroneMotionEnabled: z.boolean().optional(),
  idleDroneHeightEnabled: z.boolean().optional(),
  idleDroneHeightAmplitude: z.number().min(0).max(0.5).optional(),
  idleDroneDistanceEnabled: z.boolean().optional(),
  idleDroneDistanceAmplitude: z.number().min(0).max(0.25).optional(),
  idleDroneTargetEnabled: z.boolean().optional(),
  idleDroneTargetAmplitude: z.number().min(0).max(0.25).optional(),
  idleDroneVerticalCycles: z.number().int().min(1).max(4).optional(),
  idleDronePhaseOffsetDeg: z.number().min(0).max(360).optional(),
  idleDroneSmoothness: z.number().min(0).max(1).optional(),
  status: z.enum(["draft", "published"]).optional(),
  renderingMode: z.enum(["auto", "webgpu", "webgl2"]).optional(),
  qualityPreset: z.enum(["ultra_desktop", "high_desktop", "balanced", "mobile_high", "mobile_low", "custom"]).optional(),
  customRenderScale: z.number().min(0.1).max(2).nullable().optional(),
  customDprCap: z.number().min(0.5).max(3).nullable().optional(),
  adaptiveQualityEnabled: z.boolean().optional(),
  runtimeQualityReductionEnabled: z.boolean().optional(),
  interactionQualityReductionEnabled: z.boolean().optional(),
  deviceDetectionEnabled: z.boolean().optional(),
  glassPreset: z.enum(["performance", "standard", "premium"]).optional(),
  environmentIntensity: z.number().min(0).max(4).optional(),
  cameraFovDesktop: z.number().min(10).max(120).optional(),
  cameraFovMobile: z.number().min(10).max(120).optional(),
  cameraNearClip: z.number().min(0.001).max(100).optional(),
  cameraFarClip: z.number().min(10).max(100_000).optional(),
  cameraMinAzimuthDeg: z.number().min(-360).max(360).nullable().optional(),
  cameraMaxAzimuthDeg: z.number().min(-360).max(360).nullable().optional(),
  cameraOrbitEnabled: z.boolean().optional(),
  cameraPanEnabled: z.boolean().optional(),
  cameraZoomEnabled: z.boolean().optional(),
  cameraDampingEnabled: z.boolean().optional(),
  cameraAutoFocusEnabled: z.boolean().optional(),
  cameraHelperEnabled: z.boolean().optional(),
  cameraSensorWidthMm: z.number().min(1).max(100).optional(),
  cameraPresets: z.array(cameraPresetSchema).optional(),
  exposure: z.number().min(0).max(4).optional(),
  toneMapping: z.enum(["none", "linear", "reinhard", "cineon", "aces", "agx", "neutral"]).optional(),
  viewerUI: viewerUISchema.optional(),
  sunAzimuthDeg: z.number().min(0).max(360).optional(),
  sunElevationDeg: z.number().min(-90).max(90).optional(),
  solarControllerEnabled: z.boolean().optional(),
  solarPathMode: z.enum(["manual", "geographic"]).optional(),
  viewerTimeControlEnabled: z.boolean().optional(),
  viewerTimeHours: z.number().min(0).max(24).optional(),
  viewerTimeStartHours: z.number().min(0).max(24).optional(),
  viewerTimeEndHours: z.number().min(0).max(24).optional(),
  viewerTimeStepMinutes: z.number().int().min(1).max(240).optional(),
  solarAnchors: z.array(solarAnchorSchema).max(24).optional(),
  geoLatitude: z.number().min(-90).max(90).optional(),
  geoLongitude: z.number().min(-180).max(180).optional(),
  simulationDate: z.coerce.date().optional(),
  northOffsetDeg: z.number().min(-360).max(360).optional(),
  sunDiscEnabled: z.boolean().optional(),
  autoSunIntensityEnabled: z.boolean().optional(),
  autoSunColorEnabled: z.boolean().optional(),
  manualSunIntensity: z.number().min(0).max(10).optional(),
  manualSunColorHex: hexColorSchema.optional(),
  environmentRefreshEnabled: z.boolean().optional(),
  skyEnabled: z.boolean().optional(),
  skyTurbidity: z.number().min(0).max(20).optional(),
  skyRayleigh: z.number().min(0).max(4).optional(),
  skyMieCoefficient: z.number().min(0).max(0.1).optional(),
  skyMieDirectionalG: z.number().min(0).max(1).optional(),
  mapViewEnabled: z.boolean().optional(),
  mapViewLatitude: z.number().min(-90).max(90).nullable().optional(),
  mapViewLongitude: z.number().min(-180).max(180).nullable().optional(),
  mapViewAltitude: z.number().min(-500).max(2000).optional(),
  mapViewHeadingDeg: z.number().min(-360).max(360).optional(),
  mapViewScale: z.number().positive().max(10).optional(),
  mapViewZoom: z.number().min(0).max(22).optional(),
  mapViewPitchDeg: z.number().min(0).max(85).optional(),
  mapViewBearingDeg: z.number().min(-360).max(360).optional(),
  siteEnabled: z.boolean().optional(),
  siteRadiusM: z.number().min(100).max(2000).optional(),
  siteTerrainEnabled: z.boolean().optional(),
  siteImageryEnabled: z.boolean().optional(),
  siteImageryBrightness: z.number().min(0).max(2).optional(),
  siteOffsetX: z.number().min(-2000).max(2000).optional(),
  siteOffsetZ: z.number().min(-2000).max(2000).optional(),
  siteElevationOffset: z.number().min(-1000).max(1000).optional(),
  siteRotationDeg: z.number().min(-360).max(360).optional(),
  siteScale: z.number().positive().max(10).optional(),
  backdropEnabled: z.boolean().optional(),
  backdropImageUrl: z.string().url().nullable().optional(),
  backdropRotationDeg: z.number().min(-360).max(360).optional(),
  backdropPitchDeg: z.number().min(-90).max(90).optional(),
  backdropElevation: z.number().min(-500).max(500).optional(),
  fogEnabled: z.boolean().optional(),
  fogColor: hexColorSchema.optional(),
  fogDensity: z.number().min(0).max(0.1).optional(),
  fogMatchesSky: z.boolean().optional(),
  fogHeightBandEnabled: z.boolean().optional(),
  fogHazeEnabled: z.boolean().optional(),
  fogNoiseEnabled: z.boolean().optional(),
  fogMovementEnabled: z.boolean().optional(),
  fogSunInteractionEnabled: z.boolean().optional(),
  fogBaseHeight: z.number().min(-500).max(2000).optional(),
  fogTopHeight: z.number().min(-500).max(2000).optional(),
  fogHaze: z.number().min(0).max(1).optional(),
  fogNoiseStrength: z.number().min(0).max(1).optional(),
  fogNoiseScale: z.number().min(0.0001).max(1).optional(),
  fogWindDirectionDeg: z.number().min(0).max(360).optional(),
  fogWindSpeed: z.number().min(0).max(2).optional(),
  fogFalloff: z.number().min(0.01).max(8).optional(),
  fogMaxOpacity: z.number().min(0).max(1).optional(),
  unitColorAvailable: hexColorSchema.optional(),
  unitColorReserved: hexColorSchema.optional(),
  unitColorSold: hexColorSchema.optional(),
  unitColorSelected: hexColorSchema.optional(),
  unitBlocksEnabled: z.boolean().optional(),
  unitBlocksStatusColorsEnabled: z.boolean().optional(),
  unitBlocksXrayEnabled: z.boolean().optional(),
  unitBlocksDefaultOpacity: z.number().min(0).max(1).optional(),
  unitBlocksHoverOpacity: z.number().min(0).max(1).optional(),
  unitBlocksSelectedOpacity: z.number().min(0).max(1).optional(),
  unitBlocksSelectedOutlineEnabled: z.boolean().optional(),
  unitBlocksSelectedOutlineWidth: z.number().min(0.5).max(20).optional(),
  unitBlocksSelectedScaleEnabled: z.boolean().optional(),
  unitBlocksSelectedScale: z.number().min(1).max(1.5).optional(),
  unitBlocksSelectedFillEnabled: z.boolean().optional(),
  unitColorSelectedFill: hexColorSchema.optional(),
  unitBlocksSelectedXrayEnabled: z.boolean().optional(),
  unitPoiCameraEnabled: z.boolean().optional(),
  unitPoiCameraFov: z.number().min(10).max(120).optional(),
  unitPoiCameraDistanceMultiplier: z.number().min(0.5).max(20).optional(),
  unitPoiCameraHeightOffset: z.number().min(-20).max(20).optional(),
  unitPoiTransitionMs: z.number().min(0).max(10_000).optional(),
  unitPoiAutoOcclusionCorrection: z.boolean().optional(),
  causticsEnabled: z.boolean().optional(),
  causticsScale: z.number().min(0.05).max(3).optional(),
  causticsSpeed: z.number().min(0).max(1).optional(),
  causticsIntensityAvailable: z.number().min(0).max(3).optional(),
  causticsIntensityReserved: z.number().min(0).max(3).optional(),
  causticsIntensitySold: z.number().min(0).max(3).optional(),
  shadowsEnabled: z.boolean().optional(),
  antialiasEnabled: z.boolean().optional(),
  sections: z.array(sectionSchema).optional(),
  bloomEnabled: z.boolean().optional(),
  bloomStrength: z.number().min(0).max(3).optional(),
  bloomRadius: z.number().min(0).max(1).optional(),
  waterEnabled: z.boolean().optional(),
  waterDistortionScale: z.number().min(0).max(8).optional(),
  waterSize: z.number().min(0.1).max(10).optional(),
  waterType: z.enum(["sea", "lake", "pool", "decorative"]).optional(),
  waterWavesEnabled: z.boolean().optional(),
  waterMovementEnabled: z.boolean().optional(),
  waterSunReflectionEnabled: z.boolean().optional(),
  waterEnvReflectionEnabled: z.boolean().optional(),
  waterNormalMapEnabled: z.boolean().optional(),
  waterHeight: z.number().min(-500).max(500).optional(),
  waterColor: hexColorSchema.optional(),
  waterDeepColor: hexColorSchema.optional(),
  cloudsEnabled: z.boolean().optional(),
  cloudCoverage: z.number().min(0).max(1).optional(),
  cloudDensity: z.number().min(0).max(1).optional(),
  cloudElevation: z.number().min(0).max(1).optional(),
  cloudMovementEnabled: z.boolean().optional(),
  cloudSunLightingEnabled: z.boolean().optional(),
  cloudShadowsEnabled: z.boolean().optional(),
  cloudHeight: z.number().min(0).max(2000).optional(),
  cloudThickness: z.number().min(1).max(1000).optional(),
  cloudThreshold: z.number().min(0).max(1).optional(),
  cloudOpacity: z.number().min(0).max(1).optional(),
  cloudSoftness: z.number().min(0.01).max(1).optional(),
  cloudScale: z.number().min(0.0001).max(1).optional(),
  cloudWindSpeed: z.number().min(0).max(2).optional(),
  cloudWindDirectionDeg: z.number().min(0).max(360).optional(),
  cloudRaymarchSteps: z.number().int().min(1).max(24).optional(),
  shadowSoftness: z.number().min(0).max(10).optional(),
  lutEnabled: z.boolean().optional(),
  lutPreset: z.enum(LUT_PRESET_IDS).optional(),
  lutIntensity: z.number().min(0).max(1).optional(),
  logarithmicDepthEnabled: z.boolean().optional(),
  loadingRevealEnabled: z.boolean().optional(),
  depthOfFieldEnabled: z.boolean().optional(),
  depthOfFieldFocalLength: z.number().min(0.1).max(200).optional(),
  depthOfFieldBokehScale: z.number().min(0).max(5).optional(),
  distanceBlurEnabled: z.boolean().optional(),
  distanceBlurStartM: z.number().min(0).max(5000).optional(),
  distanceBlurFullM: z.number().min(0).max(10000).optional(),
  distanceBlurAmount: z.number().min(0).max(1).optional(),
  distanceBlurRadius: z.number().min(0).max(8).optional(),
  sunLightEnabled: z.boolean().optional(),
  sunTemperatureK: z.number().int().min(1000).max(40000).optional(),
  csmEnabled: z.boolean().optional(),
  csmCascades: z.number().int().min(1).max(4).optional(),
  csmMaxDistance: z.number().min(10).max(2000).optional(),
  csmResolution: z.number().int().min(256).max(4096).optional(),
  csmSplitMode: z.enum(["practical", "uniform", "logarithmic"]).optional(),
  csmMargin: z.number().min(0).max(1000).optional(),
  softShadowsEnabled: z.boolean().optional(),
  contactShadowsEnabled: z.boolean().optional(),
  contactShadowBlur: z.number().min(0).max(2).optional(),
  contactShadowDarkness: z.number().min(0).max(1).optional(),
  contactShadowOpacity: z.number().min(0).max(1).optional(),
  contactShadowRange: z.number().min(0.02).max(5).optional(),
  transmittedShadowsEnabled: z.boolean().optional(),
  coloredShadowsEnabled: z.boolean().optional(),
  transmittedShadowStrength: z.number().min(0).max(1).optional(),
  giEnabled: z.boolean().optional(),
  giIndirectEnabled: z.boolean().optional(),
  giAOEnabled: z.boolean().optional(),
  giBackfaceLighting: z.boolean().optional(),
  giTemporalFiltering: z.boolean().optional(),
  giScreenSpaceSampling: z.boolean().optional(),
  giIntensity: z.number().min(0).max(50).optional(),
  giAOIntensity: z.number().min(0).max(4).optional(),
  giRadius: z.number().min(0.5).max(50).optional(),
  giSliceCount: z.number().int().min(1).max(4).optional(),
  giStepCount: z.number().int().min(1).max(32).optional(),
  giExpFactor: z.number().min(0.5).max(6).optional(),
  giThickness: z.number().min(0.05).max(10).optional(),
  giLinearThickness: z.boolean().optional(),
  artificialLights: z.array(artificialLightSchema).max(64).optional(),
  volumetricLightingEnabled: z.boolean().optional(),
  sunShaftsEnabled: z.boolean().optional(),
  lightVolumesEnabled: z.boolean().optional(),
  volumetricRaymarchSteps: z.number().int().min(8).max(120).optional(),
  volumetricDensity: z.number().min(0).max(2).optional(),
  volumetricMaxDensity: z.number().min(0).max(2).optional(),
  volumetricDistanceAtten: z.number().min(0).max(10).optional(),
  ssrEnabled: z.boolean().optional(),
  ssrIntensity: z.number().min(0).max(3).optional(),
  ssrMaxDistance: z.number().min(1).max(200).optional(),
  ssrThickness: z.number().min(0.01).max(5).optional(),
  ssrQuality: z.number().min(0).max(1).optional(),
  lensFlareEnabled: z.boolean().optional(),
  lensFlareIntensity: z.number().min(0).max(3).optional(),
  motionBlurEnabled: z.boolean().optional(),
  motionBlurIntensity: z.number().min(0).max(2).optional(),
});

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ projectId: string }> }
) {
  const { projectId } = await params;
  const config = await prisma.project3DConfig.findUnique({ where: { projectId } });
  return NextResponse.json(config);
}

export async function PATCH(
  request: Request,
  { params }: { params: Promise<{ projectId: string }> }
) {
  const gate = await requireAdmin();
  if (gate instanceof NextResponse) return gate;

  const { projectId } = await params;
  const parsed = patchSchema.safeParse(await request.json());
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });
  }

  const project = await prisma.project.findUnique({ where: { id: projectId } });
  if (!project || project.deletedAt) {
    return NextResponse.json(
      { error: `No project row for "${projectId}" — run \`npm run db:seed\`.` },
      { status: 404 }
    );
  }
  const previousConfig = await prisma.project3DConfig.findUnique({ where: { projectId } });

  const data = {
    ...parsed.data,
    cameraPresets: parsed.data.cameraPresets as unknown as Prisma.InputJsonValue,
    viewerUI: parsed.data.viewerUI as unknown as Prisma.InputJsonValue,
    sections: parsed.data.sections as unknown as Prisma.InputJsonValue,
    solarAnchors: parsed.data.solarAnchors as unknown as Prisma.InputJsonValue,
    artificialLights: parsed.data.artificialLights as unknown as Prisma.InputJsonValue,
  };
  const updated = await prisma.project3DConfig.upsert({
    where: { projectId },
    update: data,
    create: { projectId, ...data },
  });

  const latestVersion = await prisma.detailModelVersion.findFirst({
    where: { projectId },
    orderBy: { version: "desc" },
  });
  if (latestVersion) await refreshExperienceDocument(prisma, projectId, latestVersion.id);

  const actor = gate.user?.email ?? gate.user?.name ?? "admin";
  await logAuditEvent({
    actor,
    actorId: gate.user?.id,
    action: "3D Experience config updated",
    entityType: "Project3DConfig",
    entityId: projectId,
    entityLabel: project.name,
    previousState: previousConfig,
    newState: updated,
  });

  return NextResponse.json(updated);
}
