"use client";

import { useEffect, useRef, useState } from "react";
import { ChevronDown, MapPin, SlidersHorizontal } from "lucide-react";
import { useAppStore } from "@/lib/store";
import { PROPERTY_TYPE_LABELS } from "@/lib/constants";
import { useT } from "@/lib/i18n/useT";
import { cn, formatPrice } from "@/lib/utils";
import { mainFieldsFor } from "@/lib/propertyTypeFields";
import { PROPERTY_TYPES, priceScaleFor } from "./FiltersForm";
import { RangeSlider } from "./RangeSlider";
import type { PropertyType } from "@/lib/types";

type Menu = "type" | "location" | "price" | "bedrooms" | "bathrooms" | "area" | "more" | null;
function Word({ children, onClick }: { children: React.ReactNode; onClick: () => void }) { return <button onClick={onClick} className="inline-flex items-center gap-1 border-b border-brand-400 px-0.5 font-bold text-brand-600 transition-colors duration-150 hover:border-brand-700 hover:text-brand-700">{children}<ChevronDown className="h-3.5 w-3.5" /></button>; }

export function SentenceFilterBar() {
  const filters = useAppStore((s) => s.filters); const setFilters = useAppStore((s) => s.setFilters); const setTransaction = useAppStore((s) => s.setTransaction); const { t, locale } = useT();
  const [menu, setMenu] = useState<Menu>(null); const rootRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (event: MouseEvent) => { if (rootRef.current && !rootRef.current.contains(event.target as Node)) setMenu(null); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  const type = filters.propertyTypes.at(-1) as PropertyType | undefined; const fields = mainFieldsFor(type); const labels = PROPERTY_TYPE_LABELS[locale]; const priceScale = priceScaleFor(filters);
  const priceActive = filters.priceMin != null || filters.priceMax != null; const areaActive = filters.areaMin != null || filters.areaMax != null;
  const words: { key: Exclude<Menu, null>; label: string; active: boolean; show: boolean }[] = [
    { key: "price", label: priceActive ? `${filters.priceMin ? formatPrice(filters.priceMin, "EUR", { compact: true }) : ""}-${filters.priceMax ? formatPrice(filters.priceMax, "EUR", { compact: true }) : ""}` : "", active: priceActive, show: true },
    { key: "bedrooms", label: filters.bedrooms != null ? `${filters.bedrooms}+ ${t("filters.bedrooms").toLowerCase()}` : "", active: filters.bedrooms != null, show: fields.includes("bedrooms") },
    { key: "bathrooms", label: filters.bathrooms != null ? `${filters.bathrooms}+ ${t("filters.bathrooms").toLowerCase()}` : "", active: filters.bathrooms != null, show: fields.includes("bathrooms") },
    { key: "area", label: areaActive ? `${filters.areaMin ?? ""}-${filters.areaMax ?? ""} m²` : "", active: areaActive, show: fields.includes("area") },
  ];
  const applied = words.filter((word) => word.active); const remaining = words.filter((word) => word.show && !word.active);
  const clear = (key: Menu) => { if (key === "price") setFilters({ priceMin: null, priceMax: null }); if (key === "bedrooms") setFilters({ bedrooms: null }); if (key === "bathrooms") setFilters({ bathrooms: null }); if (key === "area") setFilters({ areaMin: null, areaMax: null }); setMenu(null); };
  const content = menu === "type" ? <div className="grid grid-cols-2 gap-2">{PROPERTY_TYPES.map((value) => <button key={value} onClick={() => { setFilters({ propertyTypes: [value], bedrooms: null, bathrooms: null, areaMin: null, areaMax: null }); setMenu(null); }} className={cn("border px-3 py-2 text-left text-sm font-semibold", type === value ? "border-brand-500 bg-brand-50 text-brand-700" : "border-neutral-200 text-neutral-700 hover:border-neutral-400")}>{labels[value]}</button>)}</div> : menu === "location" ? <input autoFocus value={filters.location} onChange={(event) => setFilters({ location: event.target.value })} placeholder={t("filters.locationPlaceholder")} className="h-11 w-full border border-neutral-300 px-3 text-sm outline-none focus:border-brand-500" /> : menu === "price" ? <RangeSlider scale={priceScale} valueMin={filters.priceMin} valueMax={filters.priceMax} onChange={(priceMin, priceMax) => setFilters({ priceMin, priceMax })} formatValue={(value) => formatPrice(value, "EUR", { compact: true })} ariaLabel={t("filters.priceRangeAria")} /> : menu === "area" ? <RangeSlider scale={{ min: 30, max: 400, step: 10 }} valueMin={filters.areaMin} valueMax={filters.areaMax} onChange={(areaMin, areaMax) => setFilters({ areaMin, areaMax })} formatValue={(value) => `${value} m²`} ariaLabel={t("filters.areaRangeAria")} /> : menu === "bedrooms" ? <Choices values={[1,2,3,4]} selected={filters.bedrooms} onChange={(bedrooms) => { setFilters({ bedrooms }); if (bedrooms != null) setMenu(null); }} /> : menu === "bathrooms" ? <Choices values={[1,2,3]} selected={filters.bathrooms} onChange={(bathrooms) => { setFilters({ bathrooms }); if (bathrooms != null) setMenu(null); }} /> : menu === "more" ? <button onClick={() => { setFilters({ premiumOnly: !filters.premiumOnly }); setMenu(null); }} className={cn("border px-3 py-2 text-sm", filters.premiumOnly ? "border-brand-500 bg-brand-50 text-brand-700" : "border-neutral-300")}>{t("filters.premiumOnly")}</button> : null;
  return <div ref={rootRef} className="relative border-b border-neutral-100 bg-white px-5 py-3"><div className="text-lg leading-snug text-neutral-900"><span>I&apos;m looking to </span><button onClick={() => setTransaction(filters.transaction === "rent" ? "buy" : "rent")} className="border-b border-brand-400 px-0.5 font-bold text-brand-600 transition-colors duration-150 hover:border-brand-700 hover:text-brand-700">{filters.transaction === "rent" ? t("nav.rent") : t("nav.buy")}</button><span> an </span><Word onClick={() => setMenu(menu === "type" ? null : "type")}>{type ? labels[type] : t("filters.propertyType")}</Word><span> in </span><Word onClick={() => setMenu(menu === "location" ? null : "location")}><MapPin className="h-3.5 w-3.5" />{filters.location || t("filters.location")}</Word>{applied.map((word) => <span key={word.key}>, <Word onClick={() => setMenu(menu === word.key ? null : word.key)}>{word.label}</Word></span>)}.</div>{menu && <div className="absolute left-5 top-12 z-40 w-[min(30rem,calc(100%-2.5rem))] border border-neutral-200 bg-white p-3 shadow-[var(--shadow-2)]">{content}{["price","bedrooms","bathrooms","area"].includes(menu) && words.find((word) => word.key === menu)?.active && <button onClick={() => clear(menu)} className="mt-2 text-xs font-bold text-neutral-500 hover:text-brand-600">Remove this filter</button>}</div>}<div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs"><span className="text-neutral-400">Refine:</span>{remaining.map((word) => <button key={word.key} onClick={() => setMenu(word.key)} className="font-semibold text-neutral-500 transition-colors hover:text-brand-600 hover:underline">{word.key === "area" ? t("filters.areaM2") : word.key === "price" ? t("filters.priceShort") : t(`filters.${word.key}`)}</button>)}<button onClick={() => setMenu("more")} className="flex items-center gap-1 font-semibold text-neutral-500 transition-colors hover:text-brand-600 hover:underline"><SlidersHorizontal className="h-3 w-3" />{t("filters.moreFilters")}</button></div></div>;
}
function Choices({ values, selected, onChange }: { values: number[]; selected: number | null; onChange: (value: number | null) => void }) { return <div className="flex flex-wrap gap-2">{values.map((value) => <button key={value} onClick={() => onChange(selected === value ? null : value)} className={cn("border px-3 py-2 text-sm font-semibold", selected === value ? "border-brand-500 bg-brand-50 text-brand-700" : "border-neutral-300 text-neutral-700")}>{value}+</button>)}</div>; }
