-- AlterTable
ALTER TABLE "project_3d_configs" ADD COLUMN     "mapViewBearingDeg" DOUBLE PRECISION NOT NULL DEFAULT -20,
ADD COLUMN     "mapViewPitchDeg" DOUBLE PRECISION NOT NULL DEFAULT 60,
ADD COLUMN     "mapViewZoom" DOUBLE PRECISION NOT NULL DEFAULT 17.5;
