-- AlterTable
ALTER TABLE "detail_model_versions" ADD COLUMN     "castShadow" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "modelEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "modelVisible" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "positionX" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "positionZ" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "receiveShadow" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "rotationXDeg" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "rotationZDeg" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "selectable" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "transformLocked" BOOLEAN NOT NULL DEFAULT false;
